### ISSUE TITLE
Encrypt support

### ISSUE THREAD

**Issue by halukmy** [sandeepmistry/arduino-LoRa#155]
When you will add secure message support ?

**Comment by sabas1080** [comment]
Hi

you can use an encryption library

example https://github.com/rweather/arduinolibs

**Comment by halukmy** [comment]
@sabas1080  is it makes secure communication?

**Comment by wero1414** [comment]
Secure as you keep your keys hidden, if you need really secure communication you should try LoRaWAN

**Comment by sandeepmistry** [comment]
No plans to add encryption to this library.

**Comment by alaeddineth** [comment]
> No plans to add encryption to this library.

I'm doing a  projet to secure this library but I found a weird problem 
our job is actually:
Sender:
send a message that contains
* Information encrypts with aes128 with session key
* hashing with sha256
* digital signature obtained with the asymmetric curve crypto algorithm
* the session key
reciever:
* will decrypt the data with the session key (confidentiality)
* decrypt the digital signature with the shared secret key and obtain the hash to ensure authentication
* will hash the data and compare it with the hash received to verify the integrity of the data

we tested all its functions one by one, and we applied them on the lora sender, the code is successfully compiled but the output: contains nothing even the display in serial port and the message was not transmitted
I did not really understand what the problem is with insufficient memory or the arduino takes too long to calculate data or what
here is the code
and the output in screenshot
![output](https://user-images.githubusercontent.com/50785652/83665186-c0d3a600-a5d3-11ea-94a6-71c107bbe429.PNG)
![code](https://user-images.githubusercontent.com/50785652/83665188-c204d300-a5d3-11ea-9171-0d8665e2a8c1.PNG)
![lib](https://user-images.githubusercontent.com/50785652/83665193-c3360000-a5d3-11ea-9d5a-37d572baef4f.PNG)

**Comment by halukmy** [comment]
@alaeddineth can you make a sample rf tx for this ?
