### ISSUE TITLE
library 0.5.0 out of sync with Arduino IDE library manager

### ISSUE THREAD

**Issue by mfarabee** [sandeepmistry/arduino-LoRa#211]
When I install the LoRa library from the Arduino IDE (Sketch->Include Library-> Manage Libraries-> search for Lora), it will install a 0.5.0 library that is different from the 0.5.0 library that is on this GitHub site ( if I download the zip file and install from the ZIP file).
They are both tagged as version 0.5.0, but the one installed from the IDE is missing the code for inverting the IQ (as well as examples).

I apologize, I do not know enough to know where the IDE locates the libraries.

**Comment by per1234** [comment]
The [0.5.0 tag in this repository](https://github.com/sandeepmistry/arduino-LoRa/releases/tag/0.5.0) is identical to the version installed via the Arduino IDE's library manager.

I believe what you're looking at is the tip of this repository's `master` branch, which contains additional development work since the 0.5.0 release. You can see the comparison between the tip of the `master` branch and the 0.5.0 tag here:
https://github.com/sandeepmistry/arduino-LoRa/compare/0.5.0...master
That development work includes [Add function to invert IQ signal register](https://github.com/sandeepmistry/arduino-LoRa/commit/07bfead143cf617b76e19d40a291dffb5c7e3685).

Perhaps the confusion arises from the [library.properties `version` field](https://github.com/sandeepmistry/arduino-LoRa/blob/master/library.properties#L2), which is still set to 0.5.0. That is pretty much standard practice. In order to better differentiate library versions, it might be a good idea for Arduino library authors to change the library.properties `version` field to a beta value (e.g. 0.5.1-beta) immediately after tagging a stable release.

**Comment by mfarabee** [comment]
Thanks, that explains it perfectly. 
I agree, if the GitHub repository is the beta version, it would be good to tag it as such. You can close this issue, unless you want to keep it open regarding the Beta tagging.
