### ISSUE TITLE
increase the size of the transmitted packet

### ISSUE THREAD

**Issue by Smesquida** [sandeepmistry/arduino-LoRa#360]
Hi,

Is posible to increase the size of the transmitted packets via Lora to little more than 255 bytes?, is a limitation of hardware?, maybe using some kind of buffer?.

Thank you very much.

**Comment by morganrallen** [comment]
The internal buffer is only 255 bytes so there is no way to increase that. In order to work around this limitation you need to communicate between your devices how much data is expected and probably use some sort of encoding scheme to pass your data over multiple packets. But this is beyond the scope of this driver.
